language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: aatqHfUjNby4hqxcBv8MEuIhwCWSoK4OaCpIxqpKSUWihimtEyxS7k3RSBqzeajITNMHoFDyo07iW06QlLupgINBFev81Syqqjy9vxu+ikiK+S7kBCZBC93zD8n8JxFW9SCkOzyx/CWyxcIE9SiUZCV8upk9k3Dmw1yGUcxhYL3h7HPo0qnBD4aZklwfF08VzZoGDzb1hNAhNl3JbogKZIx2GimvnqCB136kUV5GhnYH/D/9yQ2dppqPQ/cdYvIvwQ9xs3Lln8UMAUAzKm55Zh3NJXHgB1v9FtaPd/IGFXzhrR06YATS0iI+/2RcZrKZ0tj20Jvuilx3CI9BoGqn4ECnnobQlwXfebAeshYpv/dOnrrY6FQHsrhnspn/QLZIPQKXoo4ssr0+/3txHBDfE85yVNrS+bx40evg4kCT/nhOFNn9zxI7QZSGygxkJJSm1Qr9IrPu9qlOyhOx9RXG+DQLk6rEXOuSfWicXf00Wwz2WzzYEIPaHud3xmE0Fbr5B4IrvVPMWiMZVbZOgOzC9PQscyoe8yrQ+u8kCjQdRBsVRDHEKpUvuBqMgIDS4g0moYYs/hrxGTVJKSvqQNXMNh4g5DJUzmenxl+MEMbrgcILDju21VEr0mfOGRY78LWxeOHdJnDCX5/xrN5Z152xAT5J8C85F1W5UD+hTdML9z0=
  app: devopstuxrs
  edge: true
