language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Fwuc8du9rGp+EqPUi/JCJly7sd3KXX4FWyxXLGyzh+i36bOwuVivPfBDPGTCgMiKRZXQobQujFV1XIJdbtN/rpUAIuLV6LHBXGKxYdaKBkTsQm5tu9PR2kARS5tny9Usdlrs+4V4/ZqtijDn3UtNZfpcDdyPdw4bOuxm9rVHNWY6hVHVkIjjyMg9dY/pb/BYQ9nZddINB59jfFo41RQbiHBzz9FiXcNEtpWZIvq0Dq7Sx0Xiv8hMsx4QEQEbrEyV2FgjpDb+YPFxceXH0b51s5lPVQZ4xt7X1KZQ37tIZtEfsecL5ASvfSxeOMzacH+ivirKNBj9K9JwDZVJf2/zztbBL8s3SP3s0YVPwFbkD6ejsrtR6QRf4AaHjQMW5jGfpMrvDZqvXVapwNObwat0WY8O99uZiyEkEiPyAwwO3CfO0hRu7z24juegf9yoLYBFhFVfmC9QU2kozarIhjWN4uJqhp5sA5tXiKVRZQryjngvCrxAotIciVlwYS0Ifbd3DsRD3WG5Z7iKqZ/10E/i7iyPsdXsbunjO87XgotumhJShL9DPT7B/26hiAzewlZflBdB4WPgSFpsEEMgweFKEiD8eCZnVBGJhZEvEqVb/mWbXQOq6VndmGU6Go2KJsi1NQpEzFCXYMEVDU4C83hQeIXtMN50pZ+MrAlyZQ7lgKg=
  app: devopstuxrs
  edge: true
