language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: hXKjppH+eVqz6m7G16b/BelF/FXfpZOkOEpNsNupE5yOc8aXpF0IJWJ8SNqVNzdq2okZOzxNhEtfDA5GrbI3Nba8eo0/ud/q0Lt1dDbnmsyq6sqC158oEnvriu8p0PR8Z62IF6Z0rvDYzVRxJTsE3UP1VpyWJzzD+rByUJYSeBkQbgOO7C/ZiyyOaoodLB90P0uc7Fiu8wr8lGGbxBuCgeLcEeVxntTFr9QLJyzamVEi5GNpLlFy+e0bZUhqwo5D+pFlDcIer9uTBRixd8R32gGLK9pbqXUBsgMGdjWItj+V8yLA7JLkfklYc/wU+tilDugu51zHXONz+Hl2xgpY+TQcmqrdPEQTtlrjdVvGpbbIcGoH6cJ8KKVtoL1oLUHnNH66uVkfLrkOEvELXArHZbMAxNMbCDgfmmaSVbS1EGuVddSq60NGhcd0JocJpZsXdeWLj8ZD+L7OV0T5nARzu7dNbvS+ElczYAqHxaF9n/JcxlkTKv358zbKF3G4rSKLwTCFI/356OHmrEi9stVqJhFExChn8BcB0funnpK7t9kG8ugt+6yUYaSWQYSDCSS/RiF9rH9OEWSe0J1fCnrpV2neeTXPmlkTUt6pY0MYnLWVwJhdOx1o/pA8ISzcyzbpdJmETRAzpsIyrtw2gPcV9jddFpuCpl7y9S5C26OYJxg=
  app: devopstuxrs
  edge: true
