language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: QSIQA7CftqUxS8z3+WSuRQBvkDENexr7R10Nwhqlo0NsVHC5GxGLTFDHf6t9GYb3tB3tchdVecDvR6LTKmSCvmhOoIoWcTazhoLyj/w+p4wiHP/AA3OGjtDucDrnJIGDuolVCpcugMFjKvZ652z6MIbjcEdY4dIS4gkI5QIZ0gSth2+9smuI13dtB1Y6Ui1G8IjHUOgNc8nwUNfADh4/Bbd890Zu5x0VFCFjzX5HTyp1JazhbEftCzrFsgN+fHdIpswj9QQmncotk20cI0Cs/M0M2nuI66Sps85Dqh+MxYyJPZcdIxJ7+pOxmiqygZJbS8/wxvUwNYaqyGX+20imU3zX6tOucQH0+G6a90sjXfYb2MdtWYvqNLe2WUpNzctCWegK7StyKPwlGnOqAu5OsI5lODHYa/1n0k7kf3/yZvU0s/Yr9BxgSBM4FMkYWbbq+Ge3XnttffgOHNUxy8vkKulTzsPZ//60QnmS8GE062bNVIEdcejZROSEptp4XnplsVQBqfxHWkat9HRHOWwvA1w86x4qR9Zy2sCAM9RnNtPKoU4PYZQeotL25gnDPLvZadqX/3NSinIrcDyvTEUB45KUhP9xDtSicpQXK2DMB+CB5kkvCQKU1vZ1MJI1MUD7iNbGQyk+Np7E/IlE2ClsBOFLJtzF1o94e14Ci9bkwCo=
  app: devopstuxrs
  edge: true
